"""pr_node — opens a GitHub pull request from the fix branch after the verifier approves."""

from __future__ import annotations

import logging
import os
import re

import httpx

logger = logging.getLogger("nodes.pr")


def _repo_full_name(repo_url: str) -> str:
    """Extract 'owner/repo' from a GitHub clone URL.

    Handles both:
      https://github.com/owner/repo.git
      git@github.com:owner/repo.git
    """
    m = re.search(r"github\.com[:/]([^/]+/[^/]+?)(?:\.git)?$", repo_url)
    return m.group(1) if m else ""


def pr_node(state: dict) -> dict:
    """Create a GitHub pull request from the pushed fix branch.

    Prerequisites (all sourced from state / env):
      - state["fix_branch"]  — the branch that was pushed by actor_node
      - state["repo_url"]    — clone URL used to identify owner/repo
      - state["task"]        — used as the PR title base
      - state["results"]     — checked to find the last successful push
      - env GITHUB_TOKEN     — personal access token with repo write scope
    """
    fix_branch = state.get("fix_branch", "")
    repo_url = state.get("repo_url", "")
    task = state.get("task", "")
    results = state.get("results", [])
    github_token = os.environ.get("GITHUB_TOKEN", "")

    # ── Guard: skip if prerequisites are missing ──────────────────────────
    if not fix_branch:
        logger.warning("pr_node: no fix_branch in state — skipping PR creation")
        return {}

    if not github_token:
        logger.warning("pr_node: GITHUB_TOKEN not set — skipping PR creation")
        return {}

    repo_name = _repo_full_name(repo_url)
    if not repo_name:
        logger.warning("pr_node: could not parse owner/repo from %r", repo_url)
        return {}

    # Verify the branch was actually pushed (last result should have push_status)
    last_push = next(
        (r.get("push_status", "") for r in reversed(results) if isinstance(r, dict)),
        "",
    )
    if "pushed ok" not in last_push:
        logger.warning(
            "pr_node: last push status was %r — branch may not exist; skipping PR",
            last_push,
        )
        return {}

    # ── Detect the default branch via the GitHub API ──────────────────────
    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    try:
        resp = httpx.get(f"https://api.github.com/repos/{repo_name}",
                         headers=headers, timeout=15)
        resp.raise_for_status()
        base_branch = resp.json().get("default_branch", "main")
    except Exception as exc:
        logger.warning("pr_node: could not fetch repo info: %s — defaulting to 'main'", exc)
        base_branch = "main"

    # ── Build PR title and body ───────────────────────────────────────────
    # Use the first line of the task as the PR title (capped at 72 chars)
    title_base = task.splitlines()[0][:72] if task else "Automated fix"
    pr_title = f"fix: {title_base}" if not title_base.lower().startswith("fix") else title_base

    # Summarise the steps and changes for the body
    step_lines = []
    for r in results:
        if not isinstance(r, dict):
            continue
        step = r.get("step", "")
        file_ = r.get("file", "")
        if step:
            step_lines.append(f"- `{file_}`: {step}" if file_ else f"- {step}")

    repro_test = state.get("repro_test", {})
    test_note = (
        f"\n\nA regression test was added at `{repro_test['path']}` to prevent "
        "this bug from reappearing."
        if repro_test.get("path") else ""
    )

    pr_body = (
        "## Summary\n\n"
        "Automated fix generated by **GH Agent** (LangGraph + Aider + E2B).\n\n"
        "### Steps applied\n\n"
        + ("\n".join(step_lines) if step_lines else "_(see diff)_")
        + test_note
        + "\n\n---\n_🤖 Generated with [GH Agent](https://github.com/michaelcafiero99/bug_fixer)_"
    )

    # ── Create the PR ─────────────────────────────────────────────────────
    try:
        resp = httpx.post(
            f"https://api.github.com/repos/{repo_name}/pulls",
            headers=headers,
            json={
                "title": pr_title,
                "body": pr_body,
                "head": fix_branch,
                "base": base_branch,
            },
            timeout=20,
        )
        resp.raise_for_status()
        pr_url = resp.json().get("html_url", "")
        pr_number = resp.json().get("number", "?")
        logger.info("PR #%s created: %s", pr_number, pr_url)
        return {"pr_url": pr_url}

    except httpx.HTTPStatusError as exc:
        body = exc.response.text[:400]
        logger.error("pr_node: GitHub API error %s — %s", exc.response.status_code, body)
        return {"pr_url": f"error: {exc.response.status_code} {body}"}
    except Exception as exc:
        logger.error("pr_node: unexpected error: %s", exc)
        return {"pr_url": f"error: {exc}"}
